### PR TITLE
Update feature branch following main

### PR DESCRIPTION
**Pull request by NanoCode012**
To allow us to compare them both from same level. Can you fix the code collisions? I could not do so. Github diff GUI is not showing the correct file for current file. I believe you only have to check the `train.py` function.

### CODE REVIEW

**Comment by MagicFrogSJTU** [comment]
@NanoCode012 Okay. I will handle this.

**Comment by NanoCode012** [comment]
I just realized my fault with this PR. I forked your branch and am updating it to follow main now.

**Comment by MagicFrogSJTU** [comment]
> I just realized my fault with this PR. I forked your branch and am updating it to follow main now.

I have finished. Check my latest branch please.

**Comment by NanoCode012** [comment]
Looking nice! I will do a trial run.

**Pull request closed without merging**
